#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 116
#define LARGE_STATE_COUNT 52
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define PRODUCTION_ID_COUNT 17

enum {
  anon_sym_EQ = 1,
  anon_sym_let = 2,
  anon_sym_SEMI = 3,
  anon_sym_dup = 4,
  aux_sym_lam_token1 = 5,
  anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH = 6,
  sym_U60_dec_literal = 7,
  aux_sym_U60_hex_literal_token1 = 8,
  aux_sym_U60_hex_literal_token2 = 9,
  sym_F60_literal = 10,
  anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH = 11,
  anon_sym_SLASH_SLASH = 12,
  aux_sym_comment_token1 = 13,
  sym__ws = 14,
  aux_sym__identifier_char_token1 = 15,
  anon_sym_DOT = 16,
  anon_sym_DOLLAR = 17,
  sym_source_file = 18,
  sym_rule = 19,
  sym__term = 20,
  sym_let = 21,
  sym_dup = 22,
  sym_lam = 23,
  sym_ctr = 24,
  sym__num = 25,
  sym_U60_hex_literal = 26,
  sym_var = 27,
  sym_comment = 28,
  sym__identifier_char = 29,
  sym_identifier = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_ctr_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_let] = "let",
  [anon_sym_SEMI] = ";",
  [anon_sym_dup] = "dup",
  [aux_sym_lam_token1] = "lam_token1",
  [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = "/[A-Z]/",
  [sym_U60_dec_literal] = "U60_dec_literal",
  [aux_sym_U60_hex_literal_token1] = "U60_hex_literal_token1",
  [aux_sym_U60_hex_literal_token2] = "U60_hex_literal_token2",
  [sym_F60_literal] = "F60_literal",
  [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = "/[a-z_$]/",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym__ws] = "_ws",
  [aux_sym__identifier_char_token1] = "_identifier_char_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_DOLLAR] = "$",
  [sym_source_file] = "source_file",
  [sym_rule] = "rule",
  [sym__term] = "_term",
  [sym_let] = "let",
  [sym_dup] = "dup",
  [sym_lam] = "lam",
  [sym_ctr] = "ctr",
  [sym__num] = "_num",
  [sym_U60_hex_literal] = "U60_hex_literal",
  [sym_var] = "var",
  [sym_comment] = "comment",
  [sym__identifier_char] = "_identifier_char",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_ctr_repeat1] = "ctr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_dup] = anon_sym_dup,
  [aux_sym_lam_token1] = aux_sym_lam_token1,
  [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
  [sym_U60_dec_literal] = sym_U60_dec_literal,
  [aux_sym_U60_hex_literal_token1] = aux_sym_U60_hex_literal_token1,
  [aux_sym_U60_hex_literal_token2] = aux_sym_U60_hex_literal_token2,
  [sym_F60_literal] = sym_F60_literal,
  [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym__ws] = sym__ws,
  [aux_sym__identifier_char_token1] = aux_sym__identifier_char_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_source_file] = sym_source_file,
  [sym_rule] = sym_rule,
  [sym__term] = sym__term,
  [sym_let] = sym_let,
  [sym_dup] = sym_dup,
  [sym_lam] = sym_lam,
  [sym_ctr] = sym_ctr,
  [sym__num] = sym__num,
  [sym_U60_hex_literal] = sym_U60_hex_literal,
  [sym_var] = sym_var,
  [sym_comment] = sym_comment,
  [sym__identifier_char] = sym__identifier_char,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_ctr_repeat1] = aux_sym_ctr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dup] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_lam_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_U60_dec_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_U60_hex_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_U60_hex_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_F60_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__identifier_char_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_dup] = {
    .visible = true,
    .named = true,
  },
  [sym_lam] = {
    .visible = true,
    .named = true,
  },
  [sym_ctr] = {
    .visible = true,
    .named = true,
  },
  [sym__num] = {
    .visible = false,
    .named = true,
  },
  [sym_U60_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_var] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier_char] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ctr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_expr = 2,
  field_lhs = 3,
  field_name = 4,
  field_name0 = 5,
  field_name1 = 6,
  field_rhs = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_expr] = "expr",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_name0] = "name0",
  [field_name1] = "name1",
  [field_rhs] = "rhs",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 2},
  [7] = {.index = 12, .length = 2},
  [8] = {.index = 14, .length = 3},
  [9] = {.index = 17, .length = 3},
  [10] = {.index = 20, .length = 4},
  [11] = {.index = 24, .length = 3},
  [12] = {.index = 27, .length = 4},
  [13] = {.index = 31, .length = 4},
  [14] = {.index = 35, .length = 4},
  [15] = {.index = 39, .length = 4},
  [16] = {.index = 43, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_lhs, 0},
    {field_rhs, 2},
  [2] =
    {field_body, 3},
    {field_name, 1},
  [4] =
    {field_lhs, 1},
    {field_rhs, 3},
  [6] =
    {field_lhs, 0},
    {field_rhs, 3},
  [8] =
    {field_lhs, 1},
    {field_rhs, 4},
  [10] =
    {field_lhs, 0},
    {field_rhs, 4},
  [12] =
    {field_lhs, 1},
    {field_rhs, 5},
  [14] =
    {field_body, 6},
    {field_expr, 4},
    {field_name, 2},
  [17] =
    {field_body, 7},
    {field_expr, 4},
    {field_name, 2},
  [20] =
    {field_body, 7},
    {field_expr, 6},
    {field_name0, 2},
    {field_name1, 4},
  [24] =
    {field_body, 8},
    {field_expr, 4},
    {field_name, 2},
  [27] =
    {field_body, 8},
    {field_expr, 7},
    {field_name0, 2},
    {field_name1, 4},
  [31] =
    {field_body, 8},
    {field_expr, 6},
    {field_name0, 2},
    {field_name1, 4},
  [35] =
    {field_body, 9},
    {field_expr, 7},
    {field_name0, 2},
    {field_name1, 4},
  [39] =
    {field_body, 9},
    {field_expr, 8},
    {field_name0, 2},
    {field_name1, 4},
  [43] =
    {field_body, 10},
    {field_expr, 8},
    {field_name0, 2},
    {field_name1, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 8,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 21,
  [25] = 14,
  [26] = 15,
  [27] = 16,
  [28] = 10,
  [29] = 29,
  [30] = 17,
  [31] = 18,
  [32] = 19,
  [33] = 23,
  [34] = 11,
  [35] = 35,
  [36] = 20,
  [37] = 37,
  [38] = 22,
  [39] = 39,
  [40] = 40,
  [41] = 9,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 13,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 47,
  [75] = 50,
  [76] = 48,
  [77] = 49,
  [78] = 51,
  [79] = 79,
  [80] = 80,
  [81] = 79,
  [82] = 82,
  [83] = 83,
  [84] = 82,
  [85] = 85,
  [86] = 83,
  [87] = 80,
  [88] = 52,
  [89] = 53,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 90,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 92,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 93,
  [103] = 103,
  [104] = 100,
  [105] = 105,
  [106] = 106,
  [107] = 105,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 106,
  [112] = 108,
  [113] = 110,
  [114] = 109,
  [115] = 115,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      if (lookahead == '$') ADVANCE(49);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(31);
      if (lookahead == ';') ADVANCE(27);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == 'd') ADVANCE(47);
      if (lookahead == 'l') ADVANCE(46);
      if (lookahead == '@' ||
          lookahead == 955) ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(49);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ';') ADVANCE(27);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '[') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'A') ADVANCE(3);
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 11:
      if (lookahead == 'Z') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(7);
      END_STATE();
    case 13:
      if (lookahead == ']') ADVANCE(8);
      END_STATE();
    case 14:
      if (lookahead == '_') ADVANCE(2);
      END_STATE();
    case 15:
      if (lookahead == '_') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'z') ADVANCE(14);
      END_STATE();
    case 19:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_dup);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_lam_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_U60_dec_literal);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '_') ADVANCE(20);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(19);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_U60_dec_literal);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '_') ADVANCE(20);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_U60_hex_literal_token1);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_U60_hex_literal_token2);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_F60_literal);
      if (lookahead == '_') ADVANCE(21);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_F60_literal);
      if (lookahead == '_') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__identifier_char_token1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym__identifier_char_token1);
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__identifier_char_token1);
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 9},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 40},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_dup] = ACTIONS(1),
    [aux_sym_lam_token1] = ACTIONS(1),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(1),
    [sym_U60_dec_literal] = ACTIONS(1),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(1),
    [sym_F60_literal] = ACTIONS(1),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
    [aux_sym__identifier_char_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(101),
    [sym_rule] = STATE(68),
    [sym__term] = STATE(96),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(23),
  },
  [2] = {
    [sym_rule] = STATE(68),
    [sym__term] = STATE(96),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(27),
  },
  [3] = {
    [sym_rule] = STATE(68),
    [sym__term] = STATE(96),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_let] = ACTIONS(31),
    [anon_sym_dup] = ACTIONS(34),
    [aux_sym_lam_token1] = ACTIONS(37),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(40),
    [sym_U60_dec_literal] = ACTIONS(43),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(46),
    [sym_F60_literal] = ACTIONS(43),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(49),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(52),
  },
  [4] = {
    [sym__term] = STATE(97),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [5] = {
    [sym__term] = STATE(97),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(55),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [6] = {
    [sym__term] = STATE(55),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(6),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(67),
  },
  [7] = {
    [sym__term] = STATE(55),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(69),
  },
  [8] = {
    [sym__term] = STATE(31),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(8),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [9] = {
    [sym__term] = STATE(102),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(9),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [10] = {
    [sym__term] = STATE(15),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(10),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [11] = {
    [sym__term] = STATE(18),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(11),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(71),
  },
  [12] = {
    [sym__term] = STATE(18),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(12),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [13] = {
    [sym__term] = STATE(20),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(13),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(73),
  },
  [14] = {
    [sym__term] = STATE(65),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(14),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [15] = {
    [sym__term] = STATE(63),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(15),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(75),
  },
  [16] = {
    [sym__term] = STATE(60),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(16),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [17] = {
    [sym__term] = STATE(59),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(17),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [18] = {
    [sym__term] = STATE(66),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(18),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(77),
  },
  [19] = {
    [sym__term] = STATE(64),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(19),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [20] = {
    [sym__term] = STATE(62),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(20),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(79),
  },
  [21] = {
    [sym__term] = STATE(58),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(21),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(81),
  },
  [22] = {
    [sym__term] = STATE(58),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(22),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [23] = {
    [sym__term] = STATE(57),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(23),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [24] = {
    [sym__term] = STATE(58),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(24),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(83),
  },
  [25] = {
    [sym__term] = STATE(65),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(25),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [26] = {
    [sym__term] = STATE(63),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(26),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(85),
  },
  [27] = {
    [sym__term] = STATE(60),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(27),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [28] = {
    [sym__term] = STATE(26),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(28),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [29] = {
    [sym__term] = STATE(73),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(29),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(87),
  },
  [30] = {
    [sym__term] = STATE(59),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(30),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [31] = {
    [sym__term] = STATE(66),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(31),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(89),
  },
  [32] = {
    [sym__term] = STATE(64),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(32),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [33] = {
    [sym__term] = STATE(57),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(33),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [34] = {
    [sym__term] = STATE(31),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(34),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(91),
  },
  [35] = {
    [sym__term] = STATE(71),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(35),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(93),
  },
  [36] = {
    [sym__term] = STATE(62),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(36),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(95),
  },
  [37] = {
    [sym__term] = STATE(70),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(37),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [38] = {
    [sym__term] = STATE(58),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(38),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [39] = {
    [sym__term] = STATE(70),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(39),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(97),
  },
  [40] = {
    [sym__term] = STATE(97),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(40),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [41] = {
    [sym__term] = STATE(93),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(41),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_dup] = ACTIONS(11),
    [aux_sym_lam_token1] = ACTIONS(13),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(15),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [42] = {
    [sym__term] = STATE(67),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(42),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [43] = {
    [sym__term] = STATE(69),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(43),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [44] = {
    [sym__term] = STATE(72),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(44),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
  },
  [45] = {
    [sym__term] = STATE(36),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(45),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(99),
  },
  [46] = {
    [sym__term] = STATE(72),
    [sym_let] = STATE(54),
    [sym_dup] = STATE(54),
    [sym_lam] = STATE(54),
    [sym_ctr] = STATE(54),
    [sym__num] = STATE(54),
    [sym_U60_hex_literal] = STATE(56),
    [sym_var] = STATE(54),
    [sym_comment] = STATE(46),
    [anon_sym_let] = ACTIONS(57),
    [anon_sym_dup] = ACTIONS(59),
    [aux_sym_lam_token1] = ACTIONS(61),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(63),
    [sym_U60_dec_literal] = ACTIONS(17),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(19),
    [sym_F60_literal] = ACTIONS(17),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(101),
  },
  [47] = {
    [sym_comment] = STATE(47),
    [sym__identifier_char] = STATE(52),
    [aux_sym_ctr_repeat1] = STATE(47),
    [ts_builtin_sym_end] = ACTIONS(103),
    [anon_sym_let] = ACTIONS(103),
    [anon_sym_dup] = ACTIONS(103),
    [aux_sym_lam_token1] = ACTIONS(103),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(103),
    [sym_U60_dec_literal] = ACTIONS(105),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(103),
    [sym_F60_literal] = ACTIONS(105),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(103),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(103),
    [aux_sym__identifier_char_token1] = ACTIONS(107),
    [anon_sym_DOT] = ACTIONS(110),
    [anon_sym_DOLLAR] = ACTIONS(110),
  },
  [48] = {
    [sym_comment] = STATE(48),
    [sym__identifier_char] = STATE(52),
    [aux_sym_ctr_repeat1] = STATE(50),
    [ts_builtin_sym_end] = ACTIONS(113),
    [anon_sym_let] = ACTIONS(113),
    [anon_sym_dup] = ACTIONS(113),
    [aux_sym_lam_token1] = ACTIONS(113),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(113),
    [sym_U60_dec_literal] = ACTIONS(115),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(113),
    [sym_F60_literal] = ACTIONS(115),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(113),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(113),
    [aux_sym__identifier_char_token1] = ACTIONS(117),
    [anon_sym_DOT] = ACTIONS(119),
    [anon_sym_DOLLAR] = ACTIONS(119),
  },
  [49] = {
    [sym_comment] = STATE(49),
    [sym__identifier_char] = STATE(52),
    [aux_sym_ctr_repeat1] = STATE(51),
    [ts_builtin_sym_end] = ACTIONS(121),
    [anon_sym_let] = ACTIONS(121),
    [anon_sym_dup] = ACTIONS(121),
    [aux_sym_lam_token1] = ACTIONS(121),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(121),
    [sym_U60_dec_literal] = ACTIONS(123),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(121),
    [sym_F60_literal] = ACTIONS(123),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(121),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(121),
    [aux_sym__identifier_char_token1] = ACTIONS(117),
    [anon_sym_DOT] = ACTIONS(119),
    [anon_sym_DOLLAR] = ACTIONS(119),
  },
  [50] = {
    [sym_comment] = STATE(50),
    [sym__identifier_char] = STATE(52),
    [aux_sym_ctr_repeat1] = STATE(47),
    [ts_builtin_sym_end] = ACTIONS(125),
    [anon_sym_let] = ACTIONS(125),
    [anon_sym_dup] = ACTIONS(125),
    [aux_sym_lam_token1] = ACTIONS(125),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(125),
    [sym_U60_dec_literal] = ACTIONS(127),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(125),
    [sym_F60_literal] = ACTIONS(127),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(125),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(125),
    [aux_sym__identifier_char_token1] = ACTIONS(117),
    [anon_sym_DOT] = ACTIONS(119),
    [anon_sym_DOLLAR] = ACTIONS(119),
  },
  [51] = {
    [sym_comment] = STATE(51),
    [sym__identifier_char] = STATE(52),
    [aux_sym_ctr_repeat1] = STATE(47),
    [ts_builtin_sym_end] = ACTIONS(129),
    [anon_sym_let] = ACTIONS(129),
    [anon_sym_dup] = ACTIONS(129),
    [aux_sym_lam_token1] = ACTIONS(129),
    [anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH] = ACTIONS(129),
    [sym_U60_dec_literal] = ACTIONS(131),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(129),
    [sym_F60_literal] = ACTIONS(131),
    [anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH] = ACTIONS(129),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym__ws] = ACTIONS(129),
    [aux_sym__identifier_char_token1] = ACTIONS(117),
    [anon_sym_DOT] = ACTIONS(119),
    [anon_sym_DOLLAR] = ACTIONS(119),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(135), 3,
      sym_U60_dec_literal,
      sym_F60_literal,
      aux_sym__identifier_char_token1,
    ACTIONS(133), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [24] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(53), 1,
      sym_comment,
    ACTIONS(139), 3,
      sym_U60_dec_literal,
      sym_F60_literal,
      aux_sym__identifier_char_token1,
    ACTIONS(137), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [48] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(54), 1,
      sym_comment,
    ACTIONS(143), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(141), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [71] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(55), 1,
      sym_comment,
    ACTIONS(147), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(145), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [94] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(56), 1,
      sym_comment,
    ACTIONS(151), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(149), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [117] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(57), 1,
      sym_comment,
    ACTIONS(155), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(153), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [140] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(58), 1,
      sym_comment,
    ACTIONS(159), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(157), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [163] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(59), 1,
      sym_comment,
    ACTIONS(163), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(161), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [186] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(60), 1,
      sym_comment,
    ACTIONS(167), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(165), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [209] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(61), 1,
      sym_comment,
    ACTIONS(171), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(169), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [232] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(62), 1,
      sym_comment,
    ACTIONS(175), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(173), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [255] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(63), 1,
      sym_comment,
    ACTIONS(179), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(177), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [278] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(64), 1,
      sym_comment,
    ACTIONS(183), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(181), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [301] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(65), 1,
      sym_comment,
    ACTIONS(187), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(185), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [324] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(66), 1,
      sym_comment,
    ACTIONS(191), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(189), 10,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [347] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(67), 1,
      sym_comment,
    ACTIONS(195), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(193), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [368] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(68), 1,
      sym_comment,
    ACTIONS(199), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(197), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [389] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(69), 1,
      sym_comment,
    ACTIONS(203), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(201), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [410] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(70), 1,
      sym_comment,
    ACTIONS(207), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(205), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [431] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(71), 1,
      sym_comment,
    ACTIONS(211), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(209), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [452] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(72), 1,
      sym_comment,
    ACTIONS(215), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(213), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [473] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(73), 1,
      sym_comment,
    ACTIONS(219), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    ACTIONS(217), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_dup,
      aux_sym_lam_token1,
      anon_sym_SLASH_LBRACKA_DASHZ_RBRACK_SLASH,
      aux_sym_U60_hex_literal_token1,
      anon_sym_SLASH_LBRACKa_DASHz_DOLLAR_RBRACK_SLASH,
      sym__ws,
  [494] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(88), 1,
      sym__identifier_char,
    STATE(74), 2,
      sym_comment,
      aux_sym_ctr_repeat1,
    ACTIONS(103), 3,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym__ws,
    ACTIONS(221), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [515] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(74), 1,
      aux_sym_ctr_repeat1,
    STATE(75), 1,
      sym_comment,
    STATE(88), 1,
      sym__identifier_char,
    ACTIONS(125), 3,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym__ws,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [538] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(75), 1,
      aux_sym_ctr_repeat1,
    STATE(76), 1,
      sym_comment,
    STATE(88), 1,
      sym__identifier_char,
    ACTIONS(113), 3,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym__ws,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [561] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(77), 1,
      sym_comment,
    STATE(78), 1,
      aux_sym_ctr_repeat1,
    STATE(88), 1,
      sym__identifier_char,
    ACTIONS(121), 3,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym__ws,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [584] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(74), 1,
      aux_sym_ctr_repeat1,
    STATE(78), 1,
      sym_comment,
    STATE(88), 1,
      sym__identifier_char,
    ACTIONS(129), 3,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym__ws,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [607] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    STATE(79), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_ctr_repeat1,
    STATE(88), 1,
      sym__identifier_char,
    STATE(110), 1,
      sym_identifier,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [631] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    STATE(80), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_ctr_repeat1,
    STATE(88), 1,
      sym__identifier_char,
    STATE(105), 1,
      sym_identifier,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [655] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    STATE(81), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_ctr_repeat1,
    STATE(88), 1,
      sym__identifier_char,
    STATE(113), 1,
      sym_identifier,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [679] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    STATE(82), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_ctr_repeat1,
    STATE(88), 1,
      sym__identifier_char,
    STATE(94), 1,
      sym_identifier,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [703] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    STATE(83), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_ctr_repeat1,
    STATE(88), 1,
      sym__identifier_char,
    STATE(106), 1,
      sym_identifier,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [727] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    STATE(84), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_ctr_repeat1,
    STATE(88), 1,
      sym__identifier_char,
    STATE(90), 1,
      sym_identifier,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [751] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(74), 1,
      aux_sym_ctr_repeat1,
    STATE(85), 1,
      sym_comment,
    STATE(88), 1,
      sym__identifier_char,
    ACTIONS(226), 2,
      anon_sym_EQ,
      sym__ws,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [773] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    STATE(85), 1,
      aux_sym_ctr_repeat1,
    STATE(86), 1,
      sym_comment,
    STATE(88), 1,
      sym__identifier_char,
    STATE(111), 1,
      sym_identifier,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [797] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    STATE(85), 1,
      aux_sym_ctr_repeat1,
    STATE(87), 1,
      sym_comment,
    STATE(88), 1,
      sym__identifier_char,
    STATE(107), 1,
      sym_identifier,
    ACTIONS(224), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [821] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(88), 1,
      sym_comment,
    ACTIONS(133), 6,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym__ws,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [836] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(89), 1,
      sym_comment,
    ACTIONS(137), 6,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym__ws,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [851] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(228), 1,
      anon_sym_EQ,
    ACTIONS(230), 1,
      sym__ws,
    STATE(90), 1,
      sym_comment,
  [864] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(232), 1,
      aux_sym_U60_hex_literal_token2,
    STATE(91), 1,
      sym_comment,
  [877] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(234), 1,
      anon_sym_EQ,
    STATE(92), 1,
      sym_comment,
  [890] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(236), 1,
      anon_sym_SEMI,
    ACTIONS(238), 1,
      sym__ws,
    STATE(93), 1,
      sym_comment,
  [903] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(240), 1,
      anon_sym_EQ,
    ACTIONS(242), 1,
      sym__ws,
    STATE(94), 1,
      sym_comment,
  [916] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(244), 1,
      anon_sym_EQ,
    STATE(95), 1,
      sym_comment,
  [929] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(246), 1,
      anon_sym_EQ,
    ACTIONS(248), 1,
      sym__ws,
    STATE(96), 1,
      sym_comment,
  [942] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(250), 1,
      anon_sym_EQ,
    ACTIONS(252), 1,
      sym__ws,
    STATE(97), 1,
      sym_comment,
  [955] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(254), 1,
      anon_sym_EQ,
    STATE(98), 1,
      sym_comment,
  [968] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(256), 1,
      anon_sym_EQ,
    STATE(99), 1,
      sym_comment,
  [981] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(258), 1,
      anon_sym_SEMI,
    STATE(100), 1,
      sym_comment,
  [994] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
    STATE(101), 1,
      sym_comment,
  [1007] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(262), 1,
      anon_sym_SEMI,
    ACTIONS(264), 1,
      sym__ws,
    STATE(102), 1,
      sym_comment,
  [1020] = 4,
    ACTIONS(266), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      aux_sym_comment_token1,
    ACTIONS(270), 1,
      sym__ws,
    STATE(103), 1,
      sym_comment,
  [1033] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(272), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_comment,
  [1046] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(274), 1,
      sym__ws,
    STATE(105), 1,
      sym_comment,
  [1056] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(276), 1,
      sym__ws,
    STATE(106), 1,
      sym_comment,
  [1066] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(278), 1,
      sym__ws,
    STATE(107), 1,
      sym_comment,
  [1076] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(280), 1,
      sym__ws,
    STATE(108), 1,
      sym_comment,
  [1086] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(282), 1,
      sym__ws,
    STATE(109), 1,
      sym_comment,
  [1096] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(284), 1,
      sym__ws,
    STATE(110), 1,
      sym_comment,
  [1106] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(286), 1,
      sym__ws,
    STATE(111), 1,
      sym_comment,
  [1116] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(288), 1,
      sym__ws,
    STATE(112), 1,
      sym_comment,
  [1126] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(290), 1,
      sym__ws,
    STATE(113), 1,
      sym_comment,
  [1136] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(292), 1,
      sym__ws,
    STATE(114), 1,
      sym_comment,
  [1146] = 1,
    ACTIONS(294), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(52)] = 0,
  [SMALL_STATE(53)] = 24,
  [SMALL_STATE(54)] = 48,
  [SMALL_STATE(55)] = 71,
  [SMALL_STATE(56)] = 94,
  [SMALL_STATE(57)] = 117,
  [SMALL_STATE(58)] = 140,
  [SMALL_STATE(59)] = 163,
  [SMALL_STATE(60)] = 186,
  [SMALL_STATE(61)] = 209,
  [SMALL_STATE(62)] = 232,
  [SMALL_STATE(63)] = 255,
  [SMALL_STATE(64)] = 278,
  [SMALL_STATE(65)] = 301,
  [SMALL_STATE(66)] = 324,
  [SMALL_STATE(67)] = 347,
  [SMALL_STATE(68)] = 368,
  [SMALL_STATE(69)] = 389,
  [SMALL_STATE(70)] = 410,
  [SMALL_STATE(71)] = 431,
  [SMALL_STATE(72)] = 452,
  [SMALL_STATE(73)] = 473,
  [SMALL_STATE(74)] = 494,
  [SMALL_STATE(75)] = 515,
  [SMALL_STATE(76)] = 538,
  [SMALL_STATE(77)] = 561,
  [SMALL_STATE(78)] = 584,
  [SMALL_STATE(79)] = 607,
  [SMALL_STATE(80)] = 631,
  [SMALL_STATE(81)] = 655,
  [SMALL_STATE(82)] = 679,
  [SMALL_STATE(83)] = 703,
  [SMALL_STATE(84)] = 727,
  [SMALL_STATE(85)] = 751,
  [SMALL_STATE(86)] = 773,
  [SMALL_STATE(87)] = 797,
  [SMALL_STATE(88)] = 821,
  [SMALL_STATE(89)] = 836,
  [SMALL_STATE(90)] = 851,
  [SMALL_STATE(91)] = 864,
  [SMALL_STATE(92)] = 877,
  [SMALL_STATE(93)] = 890,
  [SMALL_STATE(94)] = 903,
  [SMALL_STATE(95)] = 916,
  [SMALL_STATE(96)] = 929,
  [SMALL_STATE(97)] = 942,
  [SMALL_STATE(98)] = 955,
  [SMALL_STATE(99)] = 968,
  [SMALL_STATE(100)] = 981,
  [SMALL_STATE(101)] = 994,
  [SMALL_STATE(102)] = 1007,
  [SMALL_STATE(103)] = 1020,
  [SMALL_STATE(104)] = 1033,
  [SMALL_STATE(105)] = 1046,
  [SMALL_STATE(106)] = 1056,
  [SMALL_STATE(107)] = 1066,
  [SMALL_STATE(108)] = 1076,
  [SMALL_STATE(109)] = 1086,
  [SMALL_STATE(110)] = 1096,
  [SMALL_STATE(111)] = 1106,
  [SMALL_STATE(112)] = 1116,
  [SMALL_STATE(113)] = 1126,
  [SMALL_STATE(114)] = 1136,
  [SMALL_STATE(115)] = 1146,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(108),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(109),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(81),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(76),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(56),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(77),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(40),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ctr_repeat1, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ctr_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ctr_repeat1, 2), SHIFT_REPEAT(53),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctr_repeat1, 2), SHIFT_REPEAT(53),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctr, 1),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ctr, 1),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctr, 2),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ctr, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ctr_repeat1, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ctr_repeat1, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identifier_char, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__identifier_char, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term, 1),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__term, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 7, .production_id = 8),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 7, .production_id = 8),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__num, 1),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__num, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lam, 4, .production_id = 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lam, 4, .production_id = 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 8, .production_id = 9),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 8, .production_id = 9),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 9, .production_id = 13),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 9, .production_id = 13),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 10, .production_id = 14),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 10, .production_id = 14),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_U60_hex_literal, 2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_U60_hex_literal, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 8, .production_id = 10),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 8, .production_id = 10),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 10, .production_id = 15),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 10, .production_id = 15),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 9, .production_id = 11),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 9, .production_id = 11),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 11, .production_id = 16),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 11, .production_id = 16),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 9, .production_id = 12),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 9, .production_id = 12),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, .production_id = 6),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 5, .production_id = 6),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 6, .production_id = 7),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 6, .production_id = 7),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, .production_id = 4),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 4, .production_id = 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, .production_id = 3),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 4, .production_id = 3),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, .production_id = 5),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 5, .production_id = 5),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, .production_id = 1),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 3, .production_id = 1),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctr_repeat1, 2), SHIFT_REPEAT(89),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [260] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_hvm(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
