#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define PRODUCTION_ID_COUNT 16

enum {
  anon_sym_EQ = 1,
  anon_sym_let = 2,
  anon_sym_SEMI = 3,
  anon_sym_dup = 4,
  sym_U60_dec_literal = 5,
  aux_sym_U60_hex_literal_token1 = 6,
  aux_sym_U60_hex_literal_token2 = 7,
  sym_F60_literal = 8,
  anon_sym_SLASH_SLASH = 9,
  aux_sym_comment_token1 = 10,
  aux_sym__ws_token1 = 11,
  aux_sym__identifier_char_token1 = 12,
  anon_sym_DOT = 13,
  anon_sym_DOLLAR = 14,
  sym_source_file = 15,
  sym_rule = 16,
  sym__term = 17,
  sym_let = 18,
  sym_dup = 19,
  sym__num = 20,
  sym_U60_hex_literal = 21,
  sym_comment = 22,
  aux_sym__ws = 23,
  sym__identifier_char = 24,
  sym_identifier = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_identifier_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_let] = "let",
  [anon_sym_SEMI] = ";",
  [anon_sym_dup] = "dup",
  [sym_U60_dec_literal] = "U60_dec_literal",
  [aux_sym_U60_hex_literal_token1] = "U60_hex_literal_token1",
  [aux_sym_U60_hex_literal_token2] = "U60_hex_literal_token2",
  [sym_F60_literal] = "F60_literal",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym__ws_token1] = "_ws_token1",
  [aux_sym__identifier_char_token1] = "_identifier_char_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_DOLLAR] = "$",
  [sym_source_file] = "source_file",
  [sym_rule] = "rule",
  [sym__term] = "_term",
  [sym_let] = "let",
  [sym_dup] = "dup",
  [sym__num] = "_num",
  [sym_U60_hex_literal] = "U60_hex_literal",
  [sym_comment] = "comment",
  [aux_sym__ws] = "_ws",
  [sym__identifier_char] = "_identifier_char",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_identifier_repeat1] = "identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_dup] = anon_sym_dup,
  [sym_U60_dec_literal] = sym_U60_dec_literal,
  [aux_sym_U60_hex_literal_token1] = aux_sym_U60_hex_literal_token1,
  [aux_sym_U60_hex_literal_token2] = aux_sym_U60_hex_literal_token2,
  [sym_F60_literal] = sym_F60_literal,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym__ws_token1] = aux_sym__ws_token1,
  [aux_sym__identifier_char_token1] = aux_sym__identifier_char_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_source_file] = sym_source_file,
  [sym_rule] = sym_rule,
  [sym__term] = sym__term,
  [sym_let] = sym_let,
  [sym_dup] = sym_dup,
  [sym__num] = sym__num,
  [sym_U60_hex_literal] = sym_U60_hex_literal,
  [sym_comment] = sym_comment,
  [aux_sym__ws] = aux_sym__ws,
  [sym__identifier_char] = sym__identifier_char,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_identifier_repeat1] = aux_sym_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dup] = {
    .visible = true,
    .named = false,
  },
  [sym_U60_dec_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_U60_hex_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_U60_hex_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_F60_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__ws_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__identifier_char_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_dup] = {
    .visible = true,
    .named = true,
  },
  [sym__num] = {
    .visible = false,
    .named = true,
  },
  [sym_U60_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__ws] = {
    .visible = false,
    .named = false,
  },
  [sym__identifier_char] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_expr = 2,
  field_lhs = 3,
  field_name = 4,
  field_name0 = 5,
  field_name1 = 6,
  field_rhs = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_expr] = "expr",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_name0] = "name0",
  [field_name1] = "name1",
  [field_rhs] = "rhs",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 2},
  [7] = {.index = 12, .length = 3},
  [8] = {.index = 15, .length = 3},
  [9] = {.index = 18, .length = 4},
  [10] = {.index = 22, .length = 3},
  [11] = {.index = 25, .length = 4},
  [12] = {.index = 29, .length = 4},
  [13] = {.index = 33, .length = 4},
  [14] = {.index = 37, .length = 4},
  [15] = {.index = 41, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_lhs, 0},
    {field_rhs, 2},
  [2] =
    {field_lhs, 0},
    {field_rhs, 3},
  [4] =
    {field_lhs, 1},
    {field_rhs, 3},
  [6] =
    {field_lhs, 0},
    {field_rhs, 4},
  [8] =
    {field_lhs, 1},
    {field_rhs, 4},
  [10] =
    {field_lhs, 1},
    {field_rhs, 5},
  [12] =
    {field_body, 6},
    {field_expr, 4},
    {field_name, 2},
  [15] =
    {field_body, 7},
    {field_expr, 4},
    {field_name, 2},
  [18] =
    {field_body, 7},
    {field_expr, 6},
    {field_name0, 2},
    {field_name1, 4},
  [22] =
    {field_body, 8},
    {field_expr, 4},
    {field_name, 2},
  [25] =
    {field_body, 8},
    {field_expr, 6},
    {field_name0, 2},
    {field_name1, 4},
  [29] =
    {field_body, 8},
    {field_expr, 7},
    {field_name0, 2},
    {field_name1, 4},
  [33] =
    {field_body, 9},
    {field_expr, 7},
    {field_name0, 2},
    {field_name1, 4},
  [37] =
    {field_body, 9},
    {field_expr, 8},
    {field_name0, 2},
    {field_name1, 4},
  [41] =
    {field_body, 10},
    {field_expr, 8},
    {field_name0, 2},
    {field_name1, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 30,
  [54] = 37,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 68,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '$') ADVANCE(34);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(34);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '_') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(3);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '0') ADVANCE(21);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == 'd') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_dup);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_U60_dec_literal);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_U60_dec_literal);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_U60_dec_literal);
      if (lookahead == '_') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_U60_hex_literal_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_U60_hex_literal_token2);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_F60_literal);
      if (lookahead == '_') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_F60_literal);
      if (lookahead == '_') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__ws_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__identifier_char_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 15},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 15},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 15},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 15},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 15},
  [36] = {.lex_state = 15},
  [37] = {.lex_state = 15},
  [38] = {.lex_state = 15},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 15},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 15},
  [43] = {.lex_state = 15},
  [44] = {.lex_state = 15},
  [45] = {.lex_state = 15},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 15},
  [49] = {.lex_state = 15},
  [50] = {.lex_state = 15},
  [51] = {.lex_state = 15},
  [52] = {.lex_state = 15},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 29},
  [69] = {.lex_state = 9},
  [70] = {.lex_state = 29},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_U60_dec_literal] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [aux_sym__ws_token1] = ACTIONS(1),
    [aux_sym__identifier_char_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(67),
    [sym_rule] = STATE(3),
    [sym__term] = STATE(62),
    [sym_let] = STATE(62),
    [sym_dup] = STATE(62),
    [sym__num] = STATE(62),
    [sym_U60_hex_literal] = STATE(62),
    [sym_comment] = STATE(5),
    [aux_sym__ws] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_dup] = ACTIONS(7),
    [sym_U60_dec_literal] = ACTIONS(9),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(11),
    [sym_F60_literal] = ACTIONS(9),
    [anon_sym_SLASH_SLASH] = ACTIONS(13),
    [aux_sym__ws_token1] = ACTIONS(15),
  },
  [2] = {
    [sym_rule] = STATE(2),
    [sym__term] = STATE(62),
    [sym_let] = STATE(62),
    [sym_dup] = STATE(62),
    [sym__num] = STATE(62),
    [sym_U60_hex_literal] = STATE(62),
    [sym_comment] = STATE(28),
    [aux_sym__ws] = STATE(28),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_let] = ACTIONS(19),
    [anon_sym_dup] = ACTIONS(22),
    [sym_U60_dec_literal] = ACTIONS(25),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(28),
    [sym_F60_literal] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(31),
    [aux_sym__ws_token1] = ACTIONS(34),
  },
  [3] = {
    [sym_rule] = STATE(2),
    [sym__term] = STATE(62),
    [sym_let] = STATE(62),
    [sym_dup] = STATE(62),
    [sym__num] = STATE(62),
    [sym_U60_hex_literal] = STATE(62),
    [sym_comment] = STATE(4),
    [aux_sym__ws] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_dup] = ACTIONS(7),
    [sym_U60_dec_literal] = ACTIONS(9),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(11),
    [sym_F60_literal] = ACTIONS(9),
    [anon_sym_SLASH_SLASH] = ACTIONS(13),
    [aux_sym__ws_token1] = ACTIONS(39),
  },
  [4] = {
    [sym__term] = STATE(57),
    [sym_let] = STATE(57),
    [sym_dup] = STATE(57),
    [sym__num] = STATE(57),
    [sym_U60_hex_literal] = STATE(57),
    [sym_comment] = STATE(30),
    [aux_sym__ws] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(41),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_dup] = ACTIONS(7),
    [sym_U60_dec_literal] = ACTIONS(43),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(11),
    [sym_F60_literal] = ACTIONS(43),
    [anon_sym_SLASH_SLASH] = ACTIONS(13),
    [aux_sym__ws_token1] = ACTIONS(45),
  },
  [5] = {
    [sym__term] = STATE(57),
    [sym_let] = STATE(57),
    [sym_dup] = STATE(57),
    [sym__num] = STATE(57),
    [sym_U60_hex_literal] = STATE(57),
    [sym_comment] = STATE(30),
    [aux_sym__ws] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_dup] = ACTIONS(7),
    [sym_U60_dec_literal] = ACTIONS(43),
    [aux_sym_U60_hex_literal_token1] = ACTIONS(11),
    [sym_F60_literal] = ACTIONS(43),
    [anon_sym_SLASH_SLASH] = ACTIONS(13),
    [aux_sym__ws_token1] = ACTIONS(45),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(47), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(12), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [31] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(49), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(51), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [62] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(51), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(44), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [93] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(55), 1,
      aux_sym__ws_token1,
    ACTIONS(53), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(8), 2,
      sym_comment,
      aux_sym__ws,
    STATE(35), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [124] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(57), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(36), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [155] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(59), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(9), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [186] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(63), 1,
      aux_sym__ws_token1,
    ACTIONS(61), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(10), 2,
      sym_comment,
      aux_sym__ws,
    STATE(40), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [217] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(65), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(32), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [248] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(67), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(42), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [279] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(69), 1,
      aux_sym__ws_token1,
    ACTIONS(47), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(11), 2,
      sym_comment,
      aux_sym__ws,
    STATE(12), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [310] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(73), 1,
      aux_sym__ws_token1,
    ACTIONS(71), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(13), 2,
      sym_comment,
      aux_sym__ws,
    STATE(31), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [341] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(77), 1,
      aux_sym__ws_token1,
    ACTIONS(75), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(14), 2,
      sym_comment,
      aux_sym__ws,
    STATE(33), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [372] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(75), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(33), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [403] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(81), 1,
      aux_sym__ws_token1,
    ACTIONS(79), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(6), 2,
      sym_comment,
      aux_sym__ws,
    STATE(16), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [434] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(85), 1,
      aux_sym__ws_token1,
    ACTIONS(83), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(18), 2,
      sym_comment,
      aux_sym__ws,
    STATE(43), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [465] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(87), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(45), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [496] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(91), 1,
      aux_sym__ws_token1,
    ACTIONS(89), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(24), 2,
      sym_comment,
      aux_sym__ws,
    STATE(48), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [527] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(95), 1,
      aux_sym__ws_token1,
    ACTIONS(93), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(21), 2,
      sym_comment,
      aux_sym__ws,
    STATE(49), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [558] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(97), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(52), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [589] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(99), 1,
      aux_sym__ws_token1,
    ACTIONS(97), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(7), 2,
      sym_comment,
      aux_sym__ws,
    STATE(52), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [620] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(103), 1,
      aux_sym__ws_token1,
    ACTIONS(101), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(27), 2,
      sym_comment,
      aux_sym__ws,
    STATE(50), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [651] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(93), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(49), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [682] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(43), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(57), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [713] = 8,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_dup,
    ACTIONS(11), 1,
      aux_sym_U60_hex_literal_token1,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(105), 2,
      sym_U60_dec_literal,
      sym_F60_literal,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    STATE(60), 5,
      sym__term,
      sym_let,
      sym_dup,
      sym__num,
      sym_U60_hex_literal,
  [744] = 5,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(114), 1,
      aux_sym__ws_token1,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
    ACTIONS(109), 7,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
  [767] = 2,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(119), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [782] = 2,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(123), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [797] = 2,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(127), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [812] = 6,
    ACTIONS(129), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(131), 1,
      aux_sym__ws_token1,
    STATE(58), 1,
      sym_identifier,
    STATE(47), 2,
      sym__identifier_char,
      aux_sym_identifier_repeat1,
    STATE(53), 2,
      sym_comment,
      aux_sym__ws,
    ACTIONS(133), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [835] = 2,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(137), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [850] = 2,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(141), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [865] = 2,
    ACTIONS(143), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(145), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [880] = 2,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(149), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [895] = 6,
    ACTIONS(129), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(131), 1,
      aux_sym__ws_token1,
    STATE(63), 1,
      sym_identifier,
    STATE(47), 2,
      sym__identifier_char,
      aux_sym_identifier_repeat1,
    STATE(53), 2,
      sym_comment,
      aux_sym__ws,
    ACTIONS(133), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [918] = 2,
    ACTIONS(151), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(153), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [933] = 6,
    ACTIONS(129), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(131), 1,
      aux_sym__ws_token1,
    STATE(66), 1,
      sym_identifier,
    STATE(47), 2,
      sym__identifier_char,
      aux_sym_identifier_repeat1,
    STATE(53), 2,
      sym_comment,
      aux_sym__ws,
    ACTIONS(133), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [956] = 2,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(157), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [971] = 2,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(161), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [986] = 2,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(165), 8,
      anon_sym_EQ,
      anon_sym_let,
      anon_sym_SEMI,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [1001] = 2,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(169), 6,
      anon_sym_let,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [1014] = 4,
    ACTIONS(173), 1,
      aux_sym__ws_token1,
    ACTIONS(171), 2,
      anon_sym_EQ,
      anon_sym_SLASH_SLASH,
    STATE(46), 2,
      sym__identifier_char,
      aux_sym_identifier_repeat1,
    ACTIONS(175), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [1031] = 4,
    ACTIONS(180), 1,
      aux_sym__ws_token1,
    ACTIONS(178), 2,
      anon_sym_EQ,
      anon_sym_SLASH_SLASH,
    STATE(46), 2,
      sym__identifier_char,
      aux_sym_identifier_repeat1,
    ACTIONS(182), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [1048] = 2,
    ACTIONS(184), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(186), 6,
      anon_sym_let,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [1061] = 2,
    ACTIONS(188), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(190), 6,
      anon_sym_let,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [1074] = 2,
    ACTIONS(192), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(194), 6,
      anon_sym_let,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [1087] = 2,
    ACTIONS(196), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(198), 6,
      anon_sym_let,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [1100] = 2,
    ACTIONS(200), 2,
      ts_builtin_sym_end,
      aux_sym__ws_token1,
    ACTIONS(202), 6,
      anon_sym_let,
      anon_sym_dup,
      sym_U60_dec_literal,
      aux_sym_U60_hex_literal_token1,
      sym_F60_literal,
      anon_sym_SLASH_SLASH,
  [1113] = 4,
    ACTIONS(204), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(207), 1,
      aux_sym__ws_token1,
    STATE(53), 2,
      sym_comment,
      aux_sym__ws,
    ACTIONS(109), 3,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [1129] = 2,
    ACTIONS(143), 1,
      aux_sym__ws_token1,
    ACTIONS(145), 4,
      anon_sym_SLASH_SLASH,
      aux_sym__identifier_char_token1,
      anon_sym_DOT,
      anon_sym_DOLLAR,
  [1139] = 4,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(210), 1,
      anon_sym_EQ,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
  [1153] = 4,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(212), 1,
      anon_sym_EQ,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
  [1167] = 4,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(214), 1,
      anon_sym_EQ,
    ACTIONS(216), 1,
      aux_sym__ws_token1,
    STATE(55), 2,
      sym_comment,
      aux_sym__ws,
  [1181] = 4,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(218), 1,
      anon_sym_EQ,
    ACTIONS(220), 1,
      aux_sym__ws_token1,
    STATE(59), 2,
      sym_comment,
      aux_sym__ws,
  [1195] = 4,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(222), 1,
      anon_sym_EQ,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
  [1209] = 4,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(224), 1,
      anon_sym_SEMI,
    ACTIONS(226), 1,
      aux_sym__ws_token1,
    STATE(61), 2,
      sym_comment,
      aux_sym__ws,
  [1223] = 4,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 1,
      aux_sym__ws_token1,
    ACTIONS(228), 1,
      anon_sym_SEMI,
    STATE(30), 2,
      sym_comment,
      aux_sym__ws,
  [1237] = 4,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(230), 1,
      anon_sym_EQ,
    ACTIONS(232), 1,
      aux_sym__ws_token1,
    STATE(56), 2,
      sym_comment,
      aux_sym__ws,
  [1251] = 3,
    ACTIONS(129), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(234), 1,
      aux_sym__ws_token1,
    STATE(34), 2,
      sym_comment,
      aux_sym__ws,
  [1262] = 3,
    ACTIONS(129), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(236), 1,
      aux_sym__ws_token1,
    STATE(39), 2,
      sym_comment,
      aux_sym__ws,
  [1273] = 3,
    ACTIONS(129), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(238), 1,
      aux_sym__ws_token1,
    STATE(41), 2,
      sym_comment,
      aux_sym__ws,
  [1284] = 3,
    ACTIONS(13), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(240), 1,
      aux_sym__ws_token1,
    STATE(29), 2,
      sym_comment,
      aux_sym__ws,
  [1295] = 1,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
  [1299] = 1,
    ACTIONS(244), 1,
      aux_sym_comment_token1,
  [1303] = 1,
    ACTIONS(246), 1,
      aux_sym_U60_hex_literal_token2,
  [1307] = 1,
    ACTIONS(248), 1,
      aux_sym_comment_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 31,
  [SMALL_STATE(8)] = 62,
  [SMALL_STATE(9)] = 93,
  [SMALL_STATE(10)] = 124,
  [SMALL_STATE(11)] = 155,
  [SMALL_STATE(12)] = 186,
  [SMALL_STATE(13)] = 217,
  [SMALL_STATE(14)] = 248,
  [SMALL_STATE(15)] = 279,
  [SMALL_STATE(16)] = 310,
  [SMALL_STATE(17)] = 341,
  [SMALL_STATE(18)] = 372,
  [SMALL_STATE(19)] = 403,
  [SMALL_STATE(20)] = 434,
  [SMALL_STATE(21)] = 465,
  [SMALL_STATE(22)] = 496,
  [SMALL_STATE(23)] = 527,
  [SMALL_STATE(24)] = 558,
  [SMALL_STATE(25)] = 589,
  [SMALL_STATE(26)] = 620,
  [SMALL_STATE(27)] = 651,
  [SMALL_STATE(28)] = 682,
  [SMALL_STATE(29)] = 713,
  [SMALL_STATE(30)] = 744,
  [SMALL_STATE(31)] = 767,
  [SMALL_STATE(32)] = 782,
  [SMALL_STATE(33)] = 797,
  [SMALL_STATE(34)] = 812,
  [SMALL_STATE(35)] = 835,
  [SMALL_STATE(36)] = 850,
  [SMALL_STATE(37)] = 865,
  [SMALL_STATE(38)] = 880,
  [SMALL_STATE(39)] = 895,
  [SMALL_STATE(40)] = 918,
  [SMALL_STATE(41)] = 933,
  [SMALL_STATE(42)] = 956,
  [SMALL_STATE(43)] = 971,
  [SMALL_STATE(44)] = 986,
  [SMALL_STATE(45)] = 1001,
  [SMALL_STATE(46)] = 1014,
  [SMALL_STATE(47)] = 1031,
  [SMALL_STATE(48)] = 1048,
  [SMALL_STATE(49)] = 1061,
  [SMALL_STATE(50)] = 1074,
  [SMALL_STATE(51)] = 1087,
  [SMALL_STATE(52)] = 1100,
  [SMALL_STATE(53)] = 1113,
  [SMALL_STATE(54)] = 1129,
  [SMALL_STATE(55)] = 1139,
  [SMALL_STATE(56)] = 1153,
  [SMALL_STATE(57)] = 1167,
  [SMALL_STATE(58)] = 1181,
  [SMALL_STATE(59)] = 1195,
  [SMALL_STATE(60)] = 1209,
  [SMALL_STATE(61)] = 1223,
  [SMALL_STATE(62)] = 1237,
  [SMALL_STATE(63)] = 1251,
  [SMALL_STATE(64)] = 1262,
  [SMALL_STATE(65)] = 1273,
  [SMALL_STATE(66)] = 1284,
  [SMALL_STATE(67)] = 1295,
  [SMALL_STATE(68)] = 1299,
  [SMALL_STATE(69)] = 1303,
  [SMALL_STATE(70)] = 1307,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(65),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(64),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(62),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(69),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(68),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(28),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__ws, 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__ws, 2),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__ws, 2), SHIFT_REPEAT(68),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__ws, 2), SHIFT_REPEAT(30),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 8, .production_id = 9),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 8, .production_id = 9),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 9, .production_id = 11),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 9, .production_id = 11),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 8, .production_id = 8),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 8, .production_id = 8),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 10, .production_id = 14),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 10, .production_id = 14),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 10, .production_id = 13),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 10, .production_id = 13),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_U60_hex_literal, 2),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_U60_hex_literal, 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 9, .production_id = 12),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 9, .production_id = 12),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 9, .production_id = 10),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 9, .production_id = 10),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 7, .production_id = 7),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 7, .production_id = 7),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dup, 11, .production_id = 15),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dup, 11, .production_id = 15),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 6, .production_id = 6),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 6, .production_id = 6),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_identifier_repeat1, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_repeat1, 2),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_identifier_repeat1, 2), SHIFT_REPEAT(46),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, .production_id = 1),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 3, .production_id = 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, .production_id = 5),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 5, .production_id = 5),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, .production_id = 3),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 4, .production_id = 3),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, .production_id = 4),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 5, .production_id = 4),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, .production_id = 2),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 4, .production_id = 2),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__ws, 2), SHIFT_REPEAT(70),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__ws, 2), SHIFT_REPEAT(53),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [242] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_hvm(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
